### ISSUE TITLE
Uppercase character on the name of the thermostat

### ISSUE THREAD

**Issue by SmartM-ui** [danye72/smarther-v1#9]
Give the possibility to write the name of the thermostat in uppercase letters

**Comment by danye72** [comment]
the installation must provide that the package files must have the same logic as now, let me explain:

The name of the thermostat can now be: "Primo piano" (with spaces and capital letters therefore)
In the package it must be replaced "nome_termostato" with "primo_piano", then converting uppercase letters to lowercase and spaces with "_"
